### ISSUE TITLE
Feature Request : support "string[] args" as input

### ISSUE THREAD

**Issue by dPJinjo** [lecode-official/command-line-parser#2]
Currently the Parse* and Bind* methods on the CommandLineParser class take "string commandLineParameters" as input.  It might be convenient to accept "string[] args" input as well since this may be what some/most clients will have.  Internally you could string.Join(" ", args) if you wanted.  This convenience may make your API more obvious and save your customers some annoyance.

**Comment by lecode-official** [comment]
This is a great suggestion, unfortunately just using `string.Join(" ", args)` won't work as joining command line arguments back together is pretty complex, some information gets lost when the operating system parses the command line arguments and packs them into an array. Consider the following command:

```
program --file "Hello World"
```

The array will look as follows: ["program", "--file", "Hello World"]. Joining this back together using `string.Join` will result in the following string: "program --file Hello World" Now my parser has no way of figuring out that "Hello World" belongs together.

In this simple example the obvious solution would be to quote the string "Hello World" before joining it with the rest, e.g. like this:

```
for (int i = 0; i < args.Length; i++)
{
    if (args[i].Contains(" "))
        args[i] = string.Concat("\"", args[i], "\"");
}
arguments = string.Join(" ", args);
```

But it gets even worse when we get more complex examples. As it turns out, I actually tried this method when I started converting the project to .NET Core. In *nix systems such as Linux, the operating system parses the command line arguments before it passes them to the program. So unlike in Windows you are unable to get the unprocessed command line arguments. You can have a look at the admirable job, the Mono team has made to implement [Environment.CommandLine](https://github.com/mono/mono/blob/622840da567b4d705a4e997b2a5dbfba3838588d/mcs/class/corlib/System/Environment.cs#L120). Unfortunately their solution is not perfect and only works in the more simple cases.

I gave up and stuck to my solution. But I am planning on completely rewriting the Command Line Parser to be more like argparse from Python. Then I will give up the parsing via Antlr and completely parse the command line arguments by hand. This will go hand in hand with the transition to .NET Core.

Thank you very much for your suggestion anyways. As I will not be fixing this issue, I will close it for now. If you feel strongly about it, then please be welcome to reopen it or send me a pull request.
